name: Update Badge

on:
  push:
    branches: [ badges ]

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: test-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Get test count
        id: test_count
        run: |
          # Extract the 'tests' attribute from the first <testsuite> tag in the JUnit XML
          COUNT=$(grep -oP 'tests="\K[^"]+' report.xml | head -1)
          echo "count=$COUNT" >> $GITHUB_OUTPUT

      - name: Create Tests Count badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 75977b7515de20d7382f6855d44a1d97
          filename: tests_count.json
          label: "Tests Passed"
          message: ${{ steps.test_count.outputs.count }}
          color: green